name: rambling-realms-pipeline

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run pre-commit hooks
        run: |
          pip install pre-commit
          pre-commit run --all-files

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with=dev 

      - name: Run test suite
        run: |
            poetry run coverage run -m pytest
            poetry run coverage xml -o reports/coverage.xml
            poetry run genbadge coverage -i ./reports/coverage.xml -o assets/coverage.svg
            poetry run coverage report

      - name: Commit coverage badge
        if: github.ref == 'refs/heads/update_docs'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add assets/coverage.svg
          git commit -m "chore: update coverage badge [skip ci]" || echo "No changes to commit"
          git push origin update_docs
